app/administrator/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'administrator',
    __name__,
    url_prefix='/admin',
    template_folder='templates',
    static_folder='static'
)

app/administrator/routes.py
"""
    Administrator View
"""

from flask import render_template, request

from app.administrator import blueprint

from app.administrator.modules.user_services import UserServices
from app.administrator.modules.election_services import ElectionServices
from app.administrator.modules.candidate_services import CandidateServices
from app.administrator.modules.vote_services import VoteResultServices

# import forms
from app.forms import *

"""
    USERS
"""
@blueprint.route('/users')
#@login_required
def users():
    users = UserServices().show_all()
    return render_template('users.html', users=users,
                           form=CreateAccountForm())

@blueprint.route('/api/users', methods=["POST"])
def api_user():
    response = UserServices().add(request.form)
    return response

@blueprint.route('/api/users/<string:user_id>', methods=["GET", "PUT", "DELETE"])
def api_user_info(user_id):
    if request.method == "GET":
        response = UserServices(user_id).info()
    elif request.method == "DELETE":
        response = UserServices(user_id).remove()
    elif request.method == "PUT":
        response = UserServices(user_id).update(request.form)
    return response


"""
    CANDIDATES
"""
@blueprint.route('<string:election_id>/candidates', methods=["GET"])
#@login_required
def candidates(election_id):
    candidates = CandidateServices(election_id=election_id).show_all()
    print(candidates)
    return render_template('candidates.html', candidates=candidates,
                            form=CreateCandidateForm(), form2=EnrollCandidateForm())

@blueprint.route('/api/<string:election_id>/candidates', methods=["POST"])
#@login_required
def api_candidate(election_id):
    response = CandidateServices(election_id=election_id).add(request.form)
    return response

@blueprint.route('/api/<string:user_id>/enroll/<string:candidate_id>', methods=["POST"])
#@login_required
def api_enroll_candidate(user_id, candidate_id):
    response = UserServices(user_id=user_id).enroll(candidate_id)
    return response

@blueprint.route('/api/<string:election_id>/candidates/<string:candidate_id>', methods=["GET", "PUT", "DELETE"])
def api_candidate_info(election_id, candidate_id):
    if request.method == "GET":
        response = CandidateServices(candidate_id, election_id).info()
    elif request.method == "DELETE":
        response = CandidateServices(candidate_id, election_id).remove()
    elif request.method == "PUT":
        response = CandidateServices(candidate_id, election_id).update(request.form)
    return response

"""
    ELECTIONS
"""
@blueprint.route('/elections')
#@login_required
def elections():
    elections = ElectionServices().show_all()
    return render_template('elections.html', elections=elections,
                           form=CreateElectionForm())

@blueprint.route('/api/elections', methods=["POST"])
def api_election():
    response = ElectionServices().add(request.form)
    return response

@blueprint.route('/api/elections/<string:election_id>', methods=["GET", "PUT", "DELETE"])
def api_election_info(election_id):
    if request.method == "GET":
        response = ElectionServices(election_id).info()
    elif request.method == "DELETE":
        response = ElectionServices(election_id).remove()
    elif request.method == "PUT":
        response = ElectionServices(election_id).update(request.form)
    return response

"""
    VOTES
"""
@blueprint.route('/votes')
#@login_required
def votes():
    votes = VoteResultServices().show_all()
    return render_template('votes.html', votes=votes)

app/administrator/templates/candidates.html
{% extends "base_site.html" %}
{% block title %} Candidates Management {% endblock title %}
{% block stylesheets %}
{{ super() }}
<link href="{{ url_for('static', filename='vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
<div class="right_col" role="main">
    <div class="">
        <!--<div class="page-title">
      <div class="title_left">
        <h3>User Management</h3>
      </div>
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>-->
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Candidate Management <small><a href="#" class="btn btn-success btn-md" onclick="openModal()">Add New Candidate</a></small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable-buttons" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Order No</th>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Users</th>
                                    <th>Vote Count</th>
                                    <th>Images</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for candidate in candidates %}
                                <tr>
                                    <td>{{candidate.order_no}}</td>
                                    <td>{{candidate.name}}</td>
                                    <td>{{candidate.description}}</td>
                                    <td>
                                        <ul style="list-style: none;">
                                            {% for user in candidate.users %}
                                            <li>{{user.name}}</li>
                                            {% endfor %}
                                        </ul>
                                    </td>
                                    <td>{{candidate.votes}}</td>
                                    <td>{{candidate.images}}</td>
                                    <td>{{candidate.created_at}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                Action
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#" onclick="openModal2('{{candidate.id}}')">Enroll Candidates</a>
                                                </li>
                                                <li><a href="#" onclick="getCandidate('{{candidate.id}}')">Edit</a>
                                                </li>
                                                <li>
                                                    <a href="#" onclick="deleteCandidate('{{candidate.id}}')">Delete</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modalBox" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="modalBoxTitle">Add Candidate</h4>
            </div>
            <div class="modal-body">
                <form id="candidate-form" data-parsley-validate class="form-horizontal form-label-left">
                    {% for field in form if field.widget.input_type != 'hidden' %}
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{field.label.text}}<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ field(class="form-control col-md-7 col-xs-12 required") }}
                        </div>
                    </div>
                    {% endfor %}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success" onclick="addCandidate()" id="formButton">Submit</button>
            </div>
        </div>
    </div>
</div>
<div id="modalBox2" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="modalBoxTitle">Enroll User as Candidate</h4>
            </div>
            <div class="modal-body">
                <form id="user-candidate-form" data-parsley-validate class="form-horizontal form-label-left">
                    {% for field in form2 if field.widget.input_type != 'hidden' %}
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{field.label.text}}<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ field(class="form-control col-md-7 col-xs-12 required") }}
                        </div>
                    </div>
                    {% endfor %}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success" onclick="enrollUser()" id="formButton">Submit</button>
            </div>
        </div>
    </div>
</div>
<div id="confirmBox" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Confirm</h4>
            </div>
            <div class="modal-body">
                Are you sure to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="yes-btn">Yes</button>
                <button type="button" class="btn btn-info" id="no-btn">No</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
{{ super() }}
<!-- Datatables -->
<script src="{{ url_for('static', filename='vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/pdfmake/build/vfs_fonts.js') }}"></script>
<script src="{{ url_for('static', filename='build/js/confirm.js') }}"></script>
<script src="{{ url_for('static', filename='build/js/candidates.js') }}"></script>
{% endblock javascripts %}

app/administrator/templates/elections.html
{% extends "base_site.html" %}
{% block title %} Elections Management {% endblock title %}
{% block stylesheets %}
{{ super() }}
<link href="{{ url_for('static', filename='vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
<div class="right_col" role="main">
    <div class="">
        <!--<div class="page-title">
      <div class="title_left">
        <h3>User Management</h3>
      </div>
      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>-->
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Election Management <small><a href="#" class="btn btn-success btn-md" onclick="openModal()">Add New Election</a></small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Settings 1</a>
                                    </li>
                                    <li><a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="datatable-buttons" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Poster</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for election in elections %}
                                <tr>
                                    <td>{{election.name}}</td>
                                    <td>{{election.description}}</td>
                                    <td>{{election.images}}</td>
                                    <td>{{election.created_at}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                Action
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="{{ url_for('administrator.candidates', election_id=election.id) }}">View Candidates</a>
                                                </li>
                                                <li><a href="#" onclick="getElection('{{election.id}}')">Edit</a>
                                                </li>
                                                <li>
                                                    <a href="#" onclick="deleteElection('{{election.id}}')">Delete</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modalBox" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="modalBoxTitle">Add Election</h4>
            </div>
            <div class="modal-body">
                <form id="election-form" data-parsley-validate class="form-horizontal form-label-left">
                    {% for field in form if field.widget.input_type != 'hidden' %}
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{field.label.text}}<span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ field(class="form-control col-md-7 col-xs-12 required") }}
                        </div>
                    </div>
                    {% endfor %}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success" onclick="addElection()" id="formButton">Submit</button>
            </div>
        </div>
    </div>
</div>
<div id="confirmBox" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Confirm</h4>
            </div>
            <div class="modal-body">
                Are you sure to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="yes-btn">Yes</button>
                <button type="button" class="btn btn-info" id="no-btn">No</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascripts %}
{{ super() }}
<!-- Datatables -->
<script src="{{ url_for('static', filename='vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jszip/dist/jszip.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/pdfmake/build/vfs_fonts.js') }}"></script>
<script src="{{ url_for('static', filename='build/js/confirm.js') }}"></script>
<script src="{{ url_for('static', filename='build/js/elections.js') }}"></script>
{% endblock javascripts %}